// apps/dashboard/app/components/PendingAdsMenu.vue
<template>
  <div ref="menuRef" class="header-icons__dropdown-wrap">
    <button
      ref="triggerRef"
      type="button"
      class="header-icons__trigger header-icons__trigger--badge"
      title="Anuncios pendientes"
      @click="open = !open"
    >
      <Bell :size="20" class="header-icons__trigger-icon" />
      <span
        v-if="pendingCount > 0"
        class="header-icons__badge"
        :class="{
          'header-icons__badge--dot': pendingCount > 10,
        }"
      >
        <template v-if="pendingCount <= 10">{{ pendingCount }}</template>
        <Circle v-else :size="8" class="header-icons__badge-dot" />
      </span>
    </button>
    <div
      v-if="open"
      ref="panelRef"
      class="header-icons__panel header-icons__panel--list"
    >
      <div class="header-icons__panel-head">
        <h3 class="header-icons__panel-title">Anuncios Pendientes</h3>
        <NuxtLink
          to="/anuncios/pendientes"
          class="header-icons__panel-link"
          @click="open = false"
        >
          Ver todas
          <ExternalLink :size="12" class="header-icons__panel-link-icon" />
        </NuxtLink>
      </div>
      <div class="header-icons__panel-body">
        <p v-if="loading" class="header-icons__panel-message">Cargando...</p>
        <div
          v-else-if="!loading && ads.length === 0"
          class="header-icons__panel-empty"
        >
          <span class="header-icons__panel-empty-icon">
            <CheckCircle2 :size="24" />
          </span>
          <p class="header-icons__panel-empty-title">Todo al día</p>
          <p class="header-icons__panel-empty-text">
            No hay anuncios pendientes de revisión
          </p>
        </div>
        <NuxtLink
          v-for="(ad, index) in ads"
          :key="ad.id"
          :to="`/anuncios/${ad.id}`"
          class="header-icons__list-item"
          :class="{
            'header-icons__list-item--border': index < ads.length - 1,
          }"
          @click="open = false"
        >
          <div class="header-icons__list-item-main">
            <span class="header-icons__list-item-title">{{ ad.name }}</span>
            <span class="header-icons__list-item-meta">
              {{ ad.user?.username || ad.user?.email || "Usuario" }} •
              {{ formatTime(ad.createdAt) }}
            </span>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { Bell, CheckCircle2, Circle, ExternalLink } from "lucide-vue-next";

interface Ad {
  id: number;
  name: string;
  createdAt: string;
  user?: { username?: string; email?: string };
}

const strapi = useStrapi();

const open = ref(false);
const loading = ref(true);
const ads = ref<Ad[]>([]);
const pendingCount = ref(0);
const menuRef = ref<HTMLElement | null>(null);
const triggerRef = ref<HTMLElement | null>(null);
const panelRef = ref<HTMLElement | null>(null);

const fetchPendingAds = async () => {
  try {
    loading.value = true;
    const res = (await strapi.find("ads/pendings", {
      pagination: { page: 1, pageSize: 10 },
      sort: "createdAt:asc",
      populate: ["user"],
    })) as {
      data?: Ad[];
      meta?: { pagination?: { total?: number } };
    };
    ads.value = Array.isArray(res.data) ? res.data : [];
    pendingCount.value = res.meta?.pagination?.total ?? ads.value.length;
  } catch (error) {
    console.error("Error fetching pending ads:", error);
    ads.value = [];
    pendingCount.value = 0;
  } finally {
    loading.value = false;
  }
};

const formatTime = (dateString: string) => {
  return new Date(dateString).toLocaleTimeString("es-CL", {
    hour: "2-digit",
    minute: "2-digit",
  });
};

const handleClickOutside = (event: MouseEvent) => {
  if (
    menuRef.value &&
    !menuRef.value.contains(event.target as Node) &&
    open.value
  ) {
    open.value = false;
  }
};

onMounted(() => {
  fetchPendingAds();
  document.addEventListener("click", handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener("click", handleClickOutside);
});
</script>

// apps/dashboard/src/components/ui/pending-ads-menu.tsx
'use client';

import { useState, useEffect } from 'react';
import { Bell, CheckCircle2, Circle } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { getPendingAds, StrapiAd } from '@/lib/strapi';
import Link from 'next/link';
import { ExternalLink } from 'lucide-react';

export function PendingAdsMenu() {
  const [ads, setAds] = useState<StrapiAd[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPendingAds = async () => {
      try {
        setLoading(true);
        // Obtener los últimos 10 anuncios pendientes
        const response = await getPendingAds({
          page: 1,
          pageSize: 10,
          sort: 'createdAt:desc',
        });

        setAds(response.data);
      } catch (error) {
        console.error('Error fetching pending ads:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchPendingAds();
  }, []);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('es-CL', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <DropdownMenu modal={false}>
      <DropdownMenuTrigger asChild>
        <button className="relative p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-sm transition-colors">
          <Bell className="h-5 w-5" />
          {ads.length > 0 && (
            <span className="absolute top-0.5 right-0.5 bg-orange-500 text-white text-[10px] rounded-full h-4 w-4 flex items-center justify-center font-medium">
              {ads.length > 10 ? (
                <Circle className="h-2 w-2 fill-current" />
              ) : (
                ads.length
              )}
            </span>
          )}
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-96 p-4">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-semibold text-gray-900">
            Anuncios Pendientes
          </h3>
          <Link
            href="/ads/pending"
            className="text-xs text-blue-600 hover:text-blue-700 flex items-center gap-1"
          >
            Ver todas <ExternalLink className="h-3 w-3" />
          </Link>
        </div>
        <div className="border-b border-dashed border-gray-200 -mx-4"></div>
        <div className="max-h-96 overflow-y-auto -mx-4 -my-4">
          {loading ? (
            <div className="text-sm text-gray-500 text-center py-8">
              Cargando...
            </div>
          ) : ads.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-12 px-4">
              <div className="w-12 h-12 rounded-full bg-green-50 flex items-center justify-center mb-3">
                <CheckCircle2 className="h-6 w-6 text-green-500" />
              </div>
              <p className="text-sm text-gray-600 font-medium mb-1">
                Todo al día
              </p>
              <p className="text-xs text-gray-400 text-center">
                No hay anuncios pendientes de revisión
              </p>
            </div>
          ) : (
            <div className="space-y-0">
              {ads.map((ad, index) => (
                <Link
                  key={ad.id}
                  href={`/ads/${ad.id}`}
                  className={`flex items-center justify-between px-2 py-3 hover:bg-gray-50 transition-colors ${
                    index !== ads.length - 1 ? 'border-b border-gray-100' : ''
                  }`}
                >
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-gray-900 truncate">
                      {ad.name}
                    </div>
                    <div className="text-xs text-gray-500">
                      {ad.user?.username || ad.user?.email || 'Usuario'} •{' '}
                      {formatDate(ad.createdAt)}
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
