// apps/dashboard/app/components/SalesMenu.vue
<template>
  <div ref="menuRef" class="header-icons__dropdown-wrap">
    <button
      ref="triggerRef"
      type="button"
      class="header-icons__trigger"
      title="Últimas órdenes"
      @click="open = !open"
    >
      <ShoppingBag :size="20" class="header-icons__trigger-icon" />
    </button>
    <div
      v-if="open"
      ref="panelRef"
      class="header-icons__panel header-icons__panel--list"
    >
      <div class="header-icons__panel-head">
        <h3 class="header-icons__panel-title">Últimas órdenes</h3>
        <NuxtLink
          to="/ordenes"
          class="header-icons__panel-link"
          @click="open = false"
        >
          Ver todas
          <ExternalLink :size="12" class="header-icons__panel-link-icon" />
        </NuxtLink>
      </div>
      <div class="header-icons__panel-body">
        <p v-if="loading" class="header-icons__panel-message">Cargando...</p>
        <p
          v-else-if="!loading && orders.length === 0"
          class="header-icons__panel-message"
        >
          No hay órdenes
        </p>
        <NuxtLink
          v-for="(order, index) in orders"
          :key="order.id"
          :to="`/ordenes/${order.id}`"
          class="header-icons__list-item"
          :class="{
            'header-icons__list-item--border': index < orders.length - 1,
          }"
          @click="open = false"
        >
          <div class="header-icons__list-item-main">
            <span class="header-icons__list-item-title">
              {{ order.buy_order || `Orden #${order.id}` }}
            </span>
            <span class="header-icons__list-item-meta">
              {{ order.user?.username || order.user?.email || "Usuario" }} •
              {{ formatTime(order.createdAt) }}
            </span>
          </div>
          <span class="header-icons__list-item-amount">
            {{ formatCurrency(order.amount) }}
          </span>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { ShoppingBag, ExternalLink } from "lucide-vue-next";

interface Order {
  id: number;
  buy_order?: string;
  amount: number | string;
  createdAt: string;
  user?: { username?: string; email?: string };
}

const strapi = useStrapi();

const open = ref(false);
const loading = ref(true);
const orders = ref<Order[]>([]);
const menuRef = ref<HTMLElement | null>(null);
const triggerRef = ref<HTMLElement | null>(null);
const panelRef = ref<HTMLElement | null>(null);

const fetchOrders = async () => {
  try {
    loading.value = true;
    const res = (await strapi.find("orders", {
      pagination: { page: 1, pageSize: 10 },
      sort: "createdAt:desc",
      populate: ["user"],
    })) as { data?: Order[] };
    orders.value = Array.isArray(res.data) ? res.data : [];
  } catch (error) {
    console.error("Error fetching recent orders:", error);
    orders.value = [];
  } finally {
    loading.value = false;
  }
};

const formatCurrency = (amount: number | string, currency = "CLP") => {
  const num = typeof amount === "string" ? Number.parseFloat(amount) : amount;
  return new Intl.NumberFormat("es-CL", {
    style: "currency",
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(num);
};

const formatTime = (dateString: string) => {
  return new Date(dateString).toLocaleTimeString("es-CL", {
    hour: "2-digit",
    minute: "2-digit",
  });
};

const handleClickOutside = (event: MouseEvent) => {
  if (
    menuRef.value &&
    !menuRef.value.contains(event.target as Node) &&
    open.value
  ) {
    open.value = false;
  }
};

onMounted(() => {
  fetchOrders();
  document.addEventListener("click", handleClickOutside);
});

onUnmounted(() => {
  document.removeEventListener("click", handleClickOutside);
});
</script>

// apps/dashboard/src/components/ui/sales-menu.tsx
'use client';

import { useState, useEffect } from 'react';
import { ShoppingBag } from 'lucide-react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { getOrders, StrapiOrder } from '@/lib/strapi';
import Link from 'next/link';
import { ExternalLink } from 'lucide-react';

export function SalesMenu() {
  const [open, setOpen] = useState(false);
  const [orders, setOrders] = useState<StrapiOrder[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecentOrders = async () => {
      try {
        setLoading(true);
        // Obtener las últimas 10 órdenes
        const response = await getOrders({
          page: 1,
          pageSize: 10,
          sort: 'createdAt:desc',
        });

        setOrders(response.data);
      } catch (error) {
        console.error('Error fetching recent orders:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchRecentOrders();
  }, []);

  const formatCurrency = (
    amount: number | string,
    currency: string = 'CLP'
  ) => {
    const numAmount = typeof amount === 'string' ? parseFloat(amount) : amount;
    return new Intl.NumberFormat('es-CL', {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(numAmount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleTimeString('es-CL', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  return (
    <DropdownMenu modal={false} open={open} onOpenChange={setOpen}>
      <DropdownMenuTrigger asChild>
        <button className="relative p-2 text-gray-500 hover:text-gray-700 transition-colors">
          <ShoppingBag className="h-5 w-5" />
        </button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-96 p-0">
        <div className="flex items-center justify-between p-4 border-b border-dashed border-gray-200">
          <h3 className="text-sm font-semibold text-gray-900">
            Últimas órdenes
          </h3>
          <Link
            href="/sales"
            onClick={() => setOpen(false)}
            className="text-xs underline flex items-center gap-1 cursor-pointer"
            style={{ color: '#313338' }}
          >
            Ver todas{' '}
            <ExternalLink className="h-3 w-3" style={{ color: '#313338' }} />
          </Link>
        </div>
        <div>
          {loading ? (
            <div className="text-sm text-gray-500 text-center py-4">
              Cargando...
            </div>
          ) : orders.length === 0 ? (
            <div className="text-sm text-gray-500 text-center py-4">
              No hay órdenes
            </div>
          ) : (
            <div>
              {orders.map((order, index) => (
                <Link
                  key={order.id}
                  href={`/sales/${order.id}`}
                  onClick={() => setOpen(false)}
                  className={`flex items-center justify-between p-3 hover:underline transition-colors cursor-pointer ${
                    index !== orders.length - 1
                      ? 'border-b border-gray-100'
                      : ''
                  }`}
                >
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-medium text-gray-900 truncate">
                      {order.buy_order || `Orden #${order.id}`}
                    </div>
                    <div className="text-xs text-gray-500">
                      {order.user?.username || order.user?.email || 'Usuario'} •{' '}
                      {formatDate(order.createdAt)}
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-gray-900 ml-4">
                    {formatCurrency(
                      typeof order.amount === 'string'
                        ? parseFloat(order.amount)
                        : order.amount,
                      'CLP'
                    )}
                  </div>
                </Link>
              ))}
            </div>
          )}
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
