// apps/dashboard/app/components/FormLogin.vue
<template>
  <Form
    v-slot="{ errors, meta }"
    :validation-schema="schema"
    @submit="handleSubmit"
  >
    <div class="form form--login">
      <div>
        <!-- Email -->
        <div class="form-group">
          <label class="form-label" for="email">Correo Electrónico</label>
          <Field
            v-model="form.email"
            name="email"
            type="email"
            class="form-control"
            autocomplete="email"
          />
          <ErrorMessage name="email" />
        </div>

        <!-- Password -->
        <div class="form-group form-group--password">
          <label class="form-label" for="password">Contraseña</label>
          <Field
            v-model="form.password"
            name="password"
            :type="passwordType"
            class="form-control"
            autocomplete="current-password"
          />
          <button
            class="form-group--password__show-password"
            type="button"
            :title="`Mostrar/ocultar contraseña`"
            @click="handleShowPassword"
          >
            <strong v-if="passwordType !== 'password'">Ocultar</strong>
            <strong v-else>Mostrar</strong>
          </button>
          <ErrorMessage name="password" />
        </div>

        <button
          :disabled="!meta.valid || sending"
          :title="`Iniciar Sesión`"
          type="submit"
          class="btn btn--block btn--primary"
        >
          <span v-if="!sending">Iniciar Sesión</span>
          <span v-if="sending">Iniciando sesión...</span>
        </button>
      </div>
    </div>
  </Form>
</template>

<script setup>
import { ref } from "vue";
import { Field, Form, ErrorMessage } from "vee-validate";
import * as yup from "yup";
const { Swal } = useSweetAlert2();
import { useRouter } from "vue-router";
import { useAppStore } from "@/stores/app.store";
import { useNuxtApp } from "#app";
import { useLogger } from "@/composables/useLogger";

const sending = ref(false);
const { login } = useStrapiAuth();
const router = useRouter();
const appStore = useAppStore();
const { $recaptcha } = useNuxtApp();
const { logInfo } = useLogger();
const config = useRuntimeConfig();
const strapi = useStrapi();

const schema = yup.object({
  email: yup
    .string()
    .email("Correo electrónico no válido")
    .required("Correo electrónico es requerido"),
  password: yup.string().required("Contraseña es requerida"),
});

const form = ref({
  email: "",
  password: "",
});

const passwordType = ref("password");

const handleShowPassword = () => {
  passwordType.value = passwordType.value === "password" ? "text" : "password";
};

const handleSubmit = async (values) => {
  sending.value = true;

  try {
    // Execute reCAPTCHA v3
    const token = await $recaptcha.execute("submit");

    // Agregar el token al objeto de login
    await login({
      identifier: values.email,
      password: values.password,
      recaptchaToken: token,
    });

    // Obtener el usuario usando /users/me que ahora incluye role y commune
    const user = await strapi.find("users/me", {
      populate: {
        role: true,
        commune: {
          populate: "region",
        },
      },
    });

    // Verificar que el usuario tenga el role "manager" por type
    if (!user || user.role?.type !== "manager") {
      // Si no es manager, cerrar sesión y mostrar error
      const { logout } = useStrapiAuth();
      await logout();

      Swal.fire(
        "Acceso denegado",
        "Solo los usuarios con rol de manager pueden acceder al dashboard.",
        "error",
      );
      return;
    }

    // Log successful login
    logInfo(`User '${values.email}' logged in successfully.`);

    // Limpiar el referer si existe
    appStore.clearReferer();

    // Redirigir siempre al home después del login
    router.push("/");
  } catch (error) {
    let swalMessage = "Hubo un error. Por favor, inténtalo de nuevo.";
    const errorMessage = error.error?.message;

    if (errorMessage === "Your account email is not confirmed") {
      swalMessage =
        "Tu cuenta no ha sido confirmada. Por favor, revisa tu correo y sigue las instrucciones para confirmar tu cuenta.";
    } else if (errorMessage === "Invalid identifier or password") {
      swalMessage =
        "El correo electrónico o la contraseña son incorrectos. Por favor, verifica tus credenciales.";
    }

    Swal.fire("Error", swalMessage, "error");
  } finally {
    sending.value = false;
  }
};
</script>

// apps/dashboard/src/components/form-login.tsx
'use client';

import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Eye, EyeOff, Mail, Lock } from 'lucide-react';
import { login, isModerator } from '@/lib/strapi';
import { useRouter } from 'next/navigation';
import ReCAPTCHA from 'react-google-recaptcha';
import Swal from 'sweetalert2';

export default function FormLogin() {
  const router = useRouter();
  const recaptchaRef = useRef<ReCAPTCHA>(null);
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState({
    identifier: '',
    password: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      // Ejecutar reCAPTCHA
      const recaptchaToken = await recaptchaRef.current?.executeAsync();

      if (!recaptchaToken) {
        await Swal.fire({
          icon: 'warning',
          title: 'reCAPTCHA requerido',
          text: 'Por favor, completa el reCAPTCHA',
          confirmButtonText: 'Entendido',
        });
        return;
      }

      // Agregar token de reCAPTCHA a los datos del formulario
      const loginData = {
        ...formData,
        recaptchaToken,
      };

      const response = await login(loginData);

      // Verificar si el usuario es moderador
      if (!isModerator(response.user)) {
        await Swal.fire({
          icon: 'error',
          title: 'Acceso denegado',
          text: 'Solo usuarios con rol "manager" pueden acceder al sistema',
          confirmButtonText: 'Entendido',
        });
        return;
      }

      // Redirigir al dashboard
      router.push('/dashboard');
    } catch (error) {
      await Swal.fire({
        icon: 'error',
        title: 'Error al iniciar sesión',
        text:
          error instanceof Error ? error.message : 'Error al iniciar sesión',
        confirmButtonText: 'Intentar de nuevo',
      });
    } finally {
      setIsLoading(false);
      // Resetear reCAPTCHA
      recaptchaRef.current?.reset();
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="identifier">Correo electrónico</Label>
        <div className="relative">
          <Mail className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <Input
            id="identifier"
            name="identifier"
            type="email"
            placeholder="tu@email.com"
            value={formData.identifier}
            onChange={handleInputChange}
            className="pl-10"
            required
            autoComplete="email"
          />
        </div>
      </div>

      <div className="space-y-2">
        <Label htmlFor="password">Contraseña</Label>
        <div className="relative">
          <Lock className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <Input
            id="password"
            name="password"
            type={showPassword ? 'text' : 'password'}
            placeholder="••••••••"
            value={formData.password}
            onChange={handleInputChange}
            className="pl-10 pr-10"
            required
            autoComplete="current-password"
          />
          <Button
            type="button"
            variant="ghost"
            size="sm"
            className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
            onClick={() => setShowPassword(!showPassword)}
          >
            {showPassword ? (
              <EyeOff className="h-4 w-4" />
            ) : (
              <Eye className="h-4 w-4" />
            )}
          </Button>
        </div>
      </div>

      <Button type="submit" className="w-full" disabled={isLoading}>
        {isLoading ? 'Iniciando sesión...' : 'Iniciar sesión'}
      </Button>

      <ReCAPTCHA
        ref={recaptchaRef}
        sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY!}
        size="invisible"
      />
    </form>
  );
}
